config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  delete '/logout' => 'sessions#destroy'

  #omniauth callback route
  get "/auth/google_oauth2/callback" => 'sessions#google'
  #do this way to make it dynamic. If adding google, facebook and github all responding to the same place in the controller
  ## get "/auth/google_oauth2/callback" => 'sessions#create/google/name

  #edit post route
  #get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
  #update post route
  #patch 'posts/:id', to: 'posts#update'
  #delete post route
  #delete 'posts/:id/edit', to: 'posts#delete'
  #edit comment route
  #get 'posts/:post_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  #update comment route
  #patch 'posts/:post_id/comments/:id', to: 'comments#update'
  #delete comment route
  #delete 'posts/:post_id/comments/:id/edit', to: 'comments#delete'

get '/search' => 'posts#search', :as => 'search_posts'

  resources :categories do
  end 

  resources :users do
    resources :posts, only: [:new, :create, :index, :edit, :update] do
      resources :comments, only: [:new, :create, :index, :edit, :update]
    end
  end 

  resources :posts, only: [:edit, :update, :destroy] do 
    resources :comments, only: [:edit, :update, :destroy]
  end 
  
end

#resources :posts do
  #  resources :comments, only: [:new, :create, :index, :edit, :update]
  #end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :post
    belongs_to :user

    validates  :content, presence: true

    validates :post, uniqueness: { scope: :user_id, message: "can only be commented on once!"}

    scope :alpha, -> { order(:content)}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :redirect_if_not_logged_in
    before_action :find_comment, only: [:show, :edit, :update, :destroy] #in each of these actions the comment in question will be automaticaly found.
    before_action :find_post, only: [:create, :edit, :update]

    def new
        if params[:post_id] && @post = Post.find_by_id(params[:post_id])
            @comment = @post.comments.build
        else
            flash[:message] = "You can't comment on a post that does not exist!"
           redirect_to user_posts_path(current_user)
        end 
    end 

    def create
        @post = Post.find_by_id(params[:post_id]) #make into helper method
        @comment = current_user.comments.build(comment_params)
        @comment.post = @post #assigning comment to specific post
        #byebug
        if @comment.save
            redirect_to user_posts_path(current_user)
        else
          render :new  
        end
    end 

    def index
        if params[:post_id] && @post = Post.find_by_id(params[:post_id])
            @comments = @post.comments.alpha 
        else @error = "That post does not exist" if params[:post_id]
            @comments = Comment.all.alpha
        end
    end

    def edit
        #byebug
        redirect_to user_post_comments_path(@comment.post.user, @comment.post_id) if !@comment || @comment.user != current_user
    end

    def update
        #byebug
        #post = current_user.post
        redirect_to user_post_comments_path(@comment.post.user, @comment.post_id) if !@comment || @comment.user != current_user
    if @comment.update(comment_params)
        redirect_to user_post_comments_path(@comment.post.user, @comment.post_id)
    else
        render :edit
    end
    end 

    def destroy
        @comment.destroy
        redirect_to user_post_comments_path(@comment.post.user, @comment.post_id)
    end 
   

    private

    def find_post
        @post = Post.find_by_id(params[:post_id])
    end

    def find_comment
        @comment = Comment.find_by_id(params[:id])
    end 

    def comment_params
        params.require(:comment).permit(:content, :user_id, :post_id)
    end 

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1>Edit comment:</h1>

<%= render partial: "layouts/errors", locals: {object: @comment} %>

<%= form_for @comment, url: user_post_comment_path(current_user, @post, @comment), method: 'PATCH' do |f| %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit %>

<% end %>

app/views/comments/index.html.erb
<h1><%= @post.title %> comments:</h1>
<p><%= @post.content %></p>
<% @comments.each do |comment| %>
    <br>
    <br>
    <%= comment.content %>
    <br>
    <% if current_user.id == comment.user_id %>
        <%= link_to "Edit comment", edit_post_comment_path(@post, comment) %>
        <%= button_to "Delete comment", post_comment_path(@post, comment), method: :delete %>
    <% end %>
<% end %>
<%= link_to "Add a new comment", new_user_post_comment_path(current_user, @post) %>

app/views/comments/new.html.erb
<% if @post %>
<h1>Add a comment for <%= @post.title %></h1>
<% else %>
<h1>Make a comment!</h1>
<% end %>

<%= render partial: "layouts/errors", locals: {object: @comment} %>


<%= form_for [current_user, @post, @comment] do |f| %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit "Comment on this Recipe!"%>

<% end %>