config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  delete '/logout' => 'sessions#destroy'

  #omniauth callback route
  get "/auth/google_oauth2/callback" => 'sessions#google'
  #do this way to make it dynamic. If adding google, facebook and github all responding to the same place in the controller
  ## get "/auth/google_oauth2/callback" => 'sessions#create/google/name

  #edit post route
  #get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
  #update post route
  #patch 'posts/:id', to: 'posts#update'
  #delete post route
  #delete 'posts/:id/edit', to: 'posts#delete'
  #edit comment route
  #get 'posts/:post_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  #update comment route
  #patch 'posts/:post_id/comments/:id', to: 'comments#update'
  #delete comment route
  #delete 'posts/:post_id/comments/:id/edit', to: 'comments#delete'

get '/search' => 'posts#search', :as => 'search_posts'

  resources :categories do
  end 

  resources :users do
    resources :posts, only: [:new, :create, :index, :edit, :update] do
      resources :comments, only: [:new, :create, :index, :edit, :update]
    end
  end 

  resources :posts, only: [:edit, :update, :destroy] do 
    resources :comments, only: [:edit, :update, :destroy]
  end 
  
end

#resources :posts do
  #  resources :comments, only: [:new, :create, :index, :edit, :update]
  #end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  has_many :comments, dependent: :destroy #whenever you delete a post this will delete all of the posts comments too
  has_many :users, through: :comments

  validates :content, :title, presence: true

  validate :too_many_posts
  #orders anything it is called on alphabetically

  scope :most_comments, -> {left_joins(:comments).group('posts.id').order('count(comments.post_id) desc')}

  def self.search(search)
    #self.where(title: search)
    @results = Post.all.where("lower(title) LIKE :search", search: search)
    #byebug
    #if search
      ##recipe = Post.find_by(title: search)
      ##if recipe 
      ##  self.where(title: recipe)
      ##else
      ##  Post.all
      ##end 
    #else
      #Post.all
    #end 
  end 

  #def category_attributes=(attr)
  #  self.category = Category.find_or_create_by(attr) if !attr[:name].blank?
  #end 

  def too_many_posts
    
    todays_posts = user.posts.select do |p|
      p.created_at.try(:to_date) == Date.today
    end 

    if todays_posts.size > 1
      errors.add(:post_id, "can't be posted more than 2 times per day!")
    end

  end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :redirect_if_not_logged_in
    before_action :find_post, only: [:show, :edit, :update, :destroy] #in each of these actions the post will be automaticaly found.
    

    def new 
        @post = Post.new
    end 

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to user_posts_path(current_user)
        else
            render :new
        end
    end 

    def index
        #@recipes = Post.search(params[:search])

       # if params[:search_by_title] && params[:search_by_title] != ""
        #    @recipes = @recipes.where("title like ?", "%# {params[:search_by_title]}%")
       # end

        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @posts = Post.all.most_comments
        else
            flash[:message] = "That post does not exist" if params[:user_id]
            @posts = Post.all.most_comments
        end
    end 

    def show 

        redirect_to user_posts_path(current_user) if !@post
    end
    
    def edit
        redirect_to user_posts_path(current_user) if !@post || @post.user != current_user
    end 

    def update 
        redirect_to user_posts_path(current_user) if !@post || @post.user != current_user
        if @post.update(post_params)
            redirect_to user_posts_path(current_user, @post)
        else
            render :edit
        end
    end 

    def destroy
        @post.destroy
        redirect_to user_posts_path(current_user)
    end 

    def search
        #byebug
        @recipes = Post.search(params[:q])
        render :search
        #byebug
        #@recipes = Post.where("title LIKE ?", "%" + params[:q] + "%")
    end 

    private

    def find_post
        @post = Post.find_by_id(params[:id])
    end 

    def post_params
        params.require(:post).permit(:title, :content, :category_id)
    end 
end

app/helpers/posts_helper.rb
module PostsHelper
    
end

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %>:</h1>

<%= render partial: "layouts/errors", locals: {object: @post} %>

<%= form_for(@post, url: user_post_path) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>  

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.collection_select(:category_id, Category.all, :id, :name)%>
    <%= f.submit "Update Recipe!"%>
<% end %>

app/views/posts/index.html.erb
<h1>All Recipes!</h1>
<div id="recipes_container">
<% @posts.each do |post| %>
<div>
    <%= "#{post.title}" %> - <%= post.comments.size %> comment(s)
    <br>
    <%= post.content %>
    <br>
    <%= link_to "See Comments", user_post_comments_path(current_user, post)%>
    <%= button_to "Comment on this recipe", new_user_post_comment_path(current_user, post), method: :get %>
    <% if current_user.id == post.user_id %>
        <%= link_to "Edit Recipe", edit_user_post_path(post.user_id,post)%>
        <%= button_to "Delete Recipe", post_path(post), method: :delete %>
    <% end %>
    <br>
    <br>
    <br>
    </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>Add a new recipe</h1>

<%= render partial: "layouts/errors", locals: {object: @post} %>

<%= form_for(@post, url: user_posts_path) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>  

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.collection_select(:category_id, Category.all, :id, :name)%>
    <%= f.submit "Add new Recipe!"%>
    
<% end %>

app/views/posts/search.html.erb
<h1>Search Results</h1>

<% @recipes.each do |recipe| %>
<div>
    <%= recipe.title %>
    <br>
    <%= recipe.content %>
</div>
<% end%>