config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  delete '/logout' => 'sessions#destroy'

  #omniauth callback route
  get "/auth/google_oauth2/callback" => 'sessions#google'
  #do this way to make it dynamic. If adding google, facebook and github all responding to the same place in the controller
  ## get "/auth/google_oauth2/callback" => 'sessions#create/google/name

  #edit post route
  #get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
  #update post route
  #patch 'posts/:id', to: 'posts#update'
  #delete post route
  #delete 'posts/:id/edit', to: 'posts#delete'
  #edit comment route
  #get 'posts/:post_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  #update comment route
  #patch 'posts/:post_id/comments/:id', to: 'comments#update'
  #delete comment route
  #delete 'posts/:post_id/comments/:id/edit', to: 'comments#delete'

get '/search' => 'posts#search', :as => 'search_posts'

  resources :categories do
  end 

  resources :users do
    resources :posts, only: [:new, :create, :index, :edit, :update] do
      resources :comments, only: [:new, :create, :index, :edit, :update]
    end
  end 

  resources :posts, only: [:edit, :update, :destroy] do 
    resources :comments, only: [:edit, :update, :destroy]
  end 
  
end

#resources :posts do
  #  resources :comments, only: [:new, :create, :index, :edit, :update]
  #end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeShareApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <nav>
    <% if logged_in? %>
    <%= link_to "Add Recipe", new_user_post_path(current_user) %> | <%= link_to "All Recipes", user_posts_path(current_user) %> | <%= link_to "Categories", categories_path%> |
    <%= link_to "Logout", logout_path, :method => :delete %>
    <% else %>
    <%= link_to "Sign Up", signup_path%> | <%= link_to "Login", login_path%> | <%= link_to "Sign Up/Log in with Google", '/auth/google_oauth2' %>
    <% end %> | 
    <%= form_with(url: "/search", method: "get", local: true) do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>
    </nav>
  </div>
  <div>
  <% if flash[:message] %>
    <%= flash[:message] %>
  <% end %>  
  </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>